#pragma once

#define BTRC_ANONYMOUS_NAME_CAT(A, B) BTRC_ANONYMOUS_NAME_CAT_IMPL(A, B)
#define BTRC_ANONYMOUS_NAME_CAT_IMPL(A, B) A##B

#ifdef __COUNTER__
#define BTRC_ANONYMOUS_NAME(STR) BTRC_ANONYMOUS_NAME_CAT(STR, __COUNTER__)
#else
#define BTRC_ANONYMOUS_NAME(STR) BTRC_ANONYMOUS_NAME_CAT(STR, __LINE__)
#endif
